defaults:
  - base
  - _self_

module: modules.lightning_modules.baseline.no_prompt
definition: NoPrompt

mbatch_size: 8
accumulated_mbatch_size: null

max_epochs: 32

precision: 16-mixed
float32_matmul_precision: highest
